In [2]:
import numpy as np

### Python list vs array

In [10]:
spike_counts = [3, 5, 2, 8, 4] #list


In [11]:
spike_counts * 2 # Python repeats the list two times

[3, 5, 2, 8, 4, 3, 5, 2, 8, 4]

In [12]:
## in Numpy
spike_counts = np.array([3, 5, 2, 8, 4])
spike_counts * 2 ## element wise multiplication

array([ 6, 10,  4, 16,  8])

### Numpy arrays

In [8]:
# zeros
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [13]:
# ones
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [16]:
# A range of numbers:
t = np.arange(0, 11, 2) #start at 0, stop before 10, step by 1
t

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# Evenly spaced values
t = np.linspace(0, 1, 11)
t

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [17]:
# One dimensional arrays
x = np.array([3, 5, 2, 8, 4])
x.shape

(5,)

In [18]:
## two dimensional arrays
raster = np.array([
    [0, 1, 0, 0, 1],
    [1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0]
])
raster.shape

(3, 5)

In [19]:
## slicing
spike_counts = np.array([3, 5, 2, 8, 4])

In [20]:
## first three values 
spike_counts[0:3]

array([3, 5, 2])

In [20]:
## index 2 to the end
spike_counts[2:]

array([2, 8, 4])

In [21]:
## for 2D
raster = np.array([
    [0, 1, 0, 0, 1],
    [1, 0, 0, 1, 0],
    [0, 0, 1, 0, 0]
])
## first row

raster[0, 2:]

array([0, 0, 1])

In [23]:
## last column

raster[:, 4]

array([1, 0, 0])

### Vectorised operations

In [24]:
spike_counts = np.array([3, 5, 2, 8, 4])
duration = 10

firing_rates = spike_counts / duration
firing_rates

array([0.3, 0.5, 0.2, 0.8, 0.4])

In [25]:
## other operations
spike_counts + 1
spike_counts * 2
spike_counts ** 2

array([ 9, 25,  4, 64, 16])

### Summary statistics

In [26]:
## mean
print("mean =", np.mean(spike_counts))

## median
print("median =", np.median(spike_counts))

## standard deviation
print("std =", np.std(spike_counts))

## minimum
print("min =", np.min(spike_counts))

## maximum
print("max =", np.max(spike_counts))

## sum
print("sum =", np.sum(spike_counts))

## diff
print("diff =", np.diff(spike_counts))

mean = 4.4
median = 4.0
std = 2.0591260281974
min = 2
max = 8
sum = 22
diff = [ 2 -3  6 -4]


### Axes

In [32]:
raster

array([[0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [34]:
## sum of all spikes
print(raster.sum())

5


In [35]:
## sum along axis 0
raster.sum(axis=0)

array([1, 1, 1, 1, 1])

In [36]:
# along axis 1
raster.sum(axis=1)

array([2, 2, 1])

In [38]:
print(raster.sum(axis=0))   # activity over time
print(raster.sum(axis=1))   # spike count per neuron

[1 1 1 1 1]
[2 2 1]


### Boolean arrays and masking

In [39]:
firing_rates = np.array([0.3, 0.5, 0.2, 0.8, 0.4])

## Find which neurons have firing rate greater then 0.4
firing_rates > 0.4

array([False,  True, False,  True, False])

In [40]:
# mask
firing_rates[firing_rates > 0.4]

array([0.5, 0.8])

In [27]:
# Ex 1
active_neurons = firing_rates > 0.4
firing_rates[active_neurons]

array([0.5, 0.8])

In [42]:
# Ex 2
rates = np.array([2.1, 5.3, 0.8, 10.2])
regions = np.array(["VISp", "VISp", "LGN", "CA1"])

rates[regions == "VISp"]

array([2.1, 5.3])

### Random numbers

In [30]:
# Generate 5 random numbers between 0 and 1
np.random.rand(5)

array([0.52803216, 0.61234339, 0.91563968, 0.1542272 , 0.42395614])

In [35]:
rng = np.random.default_rng(62) ## seed = 42, The 42 is a random seed. It makes the result reproducible.
rng.random(5)

array([0.60932017, 0.7477733 , 0.78069738, 0.28785533, 0.69323641])

In [36]:
rng.random(5)

array([0.92607276, 0.51363499, 0.87394989, 0.82672049, 0.23574655])

In [37]:
rng = np.random.default_rng(42) ## seed = 42, The 42 is a random seed. It makes the result reproducible.
rng.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [38]:
## generate random spike counts
rng.poisson(lam=2, size=10)

array([3, 3, 2, 1, 5, 2, 0, 1, 3, 1])

In [39]:
## generate a random raster
raster = rng.random((5, 100)) < 0.01 ## creates a boolean 
raster = raster.astype(int) # convert to integer
raster 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,

In [56]:
## a full example

rng = np.random.default_rng(42)

n_neurons = 5
n_time_bins = 100
spike_probability = 0.02

raster = rng.random((n_neurons, n_time_bins)) < spike_probability
raster = raster.astype(int) # convert to integer
raster

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0,

### Broadcasting

In [60]:
# Matrix X has shape (3, 3)
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Row vector b has shape (3,)
b = np.array([10, 20, 30])

print("X shape:", X.shape)
print("b shape:", b.shape)

# Broadcasting operation
Y = X + b

print(Y)

X shape: (3, 3)
b shape: (3,)
[[11 22 33]
 [14 25 36]
 [17 28 39]]


### NaNs and missing values

In [61]:
## Real data often has missing values

In [40]:
x = np.array([1.0, 2.0, np.nan, 4.0])
x

array([ 1.,  2., nan,  4.])

In [41]:
print(np.mean(x))

nan


In [66]:
## ignore nans
print(np.nanmean(x))

2.3333333333333335


In [67]:
## check for nans
print(np.isnan(x))

[False False  True False]


In [42]:
## count the number of missing values
print(np.isnan(x).sum())

1


## reshaping

In [43]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
x.reshape([3, 4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
## flatten back to 1D
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# linear algebra

In [46]:
## dot product
np.dot(3, 4)

np.int64(12)

In [50]:
a = [[1, 0, 2], [0, 1, 3]]
b = [[4, 1], [2, 2], [4, 7]]
np.dot(a, b)

array([[12, 15],
       [14, 23]])

In [53]:
np.diag((6, 2, 8))

array([[6, 0, 0],
       [0, 2, 0],
       [0, 0, 8]])

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
from numpy import linalg as LA

eigenvalues, eigenvectors = LA.eig(np.diag((6, 2, 8)))

In [56]:
eigenvalues

array([6., 2., 8.])

In [57]:
eigenvectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
a = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])
LA.inv(a)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

In [66]:
AA = np.array([[1.9999999, 3], [4, 6]])
AA
LA.inv(AA)


array([[-9999999.99416133,  4999999.99708067],
       [ 6666666.66277422, -3333333.16472044]])

In [67]:
LA.det(AA)

np.float64(-6.000000003503207e-07)

# Numba

In [68]:
pip install numba

Note: you may need to restart the kernel to use updated packages.


In [69]:
import numba

In [70]:
## First example

## A normal Python example

def sum_squares_python(x):
    total = 0.0

    for i in range(len(x)):
        total += x[i] ** 2

    return total

In [71]:
## A numba version

from numba import njit

@njit # use the decorator
def sum_squares_numba(x):
    total = 0.0

    for i in range(len(x)):
        total += x[i] ** 2

    return total

In [72]:
## Use it

x = np.random.random(1000000)

print(sum_squares_python(x))
print(sum_squares_numba(x))

333279.1586950143
333279.1586950143


In [73]:
%timeit sum_squares_python(x)
%timeit sum_squares_numba(x)

78.1 ms ± 969 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
529 μs ± 411 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## A neuroscience example

### Suppose each row is a feature vector for a neuron, and we want pairwise Euclidean distances.

In [74]:
# -------------------------------
# 1. Simple Python version
# -------------------------------
def pairwise_distances_python(X):
    n, d = X.shape
    D = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            total = 0.0

            for k in range(d):
                diff = X[i, k] - X[j, k]
                total += diff * diff

            D[i, j] = np.sqrt(total)

    return D

In [75]:
# -------------------------------
# 2. Numba version
# -------------------------------
@njit
def pairwise_distances_numba(X):
    n, d = X.shape
    D = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            total = 0.0

            for k in range(d):
                diff = X[i, k] - X[j, k]
                total += diff * diff

            D[i, j] = np.sqrt(total)

    return D

In [76]:
# -------------------------------
# 3. Create example data
# -------------------------------
rng = np.random.default_rng(42)

n = 300      # number of points / neurons
d = 50       # number of features / time bins

X = rng.random((n, d))


# -------------------------------
# 4. Warm up Numba
# -------------------------------
# The first call compiles the function.
# Do not include this compilation time in the timing comparison.
D_numba = pairwise_distances_numba(X)


# -------------------------------
# 5. Check correctness
# -------------------------------
D_python = pairwise_distances_python(X)

print("Are results close?", np.allclose(D_python, D_numba))

Are results close? True


In [77]:
# First call compiles
pairwise_distances_numba(X)

# Then time it
%timeit pairwise_distances_python(X)
%timeit pairwise_distances_numba(X)

624 ms ± 8.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
890 μs ± 2.56 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## parallel `numba` with `prange`

In [78]:
from numba import njit, prange

## Use prange when different loop iterations are independent.

@njit(parallel=True)
def pairwise_distances_parallel(X):
    n, d = X.shape
    D = np.zeros((n, n))

    for i in prange(n):
        for j in range(n):
            total = 0.0

            for k in range(d):
                diff = X[i, k] - X[j, k]
                total += diff * diff

            D[i, j] = np.sqrt(total)

    return D

In [79]:
D_parallel = pairwise_distances_parallel(X)
D_parallel

array([[0.        , 2.63295011, 2.79095946, ..., 2.73483448, 2.70348132,
        3.12583354],
       [2.63295011, 0.        , 2.77272801, ..., 2.86433706, 2.71338368,
        2.88638794],
       [2.79095946, 2.77272801, 0.        , ..., 2.73005165, 2.2047667 ,
        2.77379676],
       ...,
       [2.73483448, 2.86433706, 2.73005165, ..., 0.        , 2.6034191 ,
        2.64771157],
       [2.70348132, 2.71338368, 2.2047667 , ..., 2.6034191 , 0.        ,
        2.70922078],
       [3.12583354, 2.88638794, 2.77379676, ..., 2.64771157, 2.70922078,
        0.        ]])

In [80]:
%timeit pairwise_distances_python(X)
%timeit pairwise_distances_numba(X)
%timeit pairwise_distances_parallel(X)

610 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
886 μs ± 2.89 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
298 μs ± 11.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
